# Generated by Django 4.0.3 on 2022-04-02 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affectStat', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Champions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championName', models.CharField(max_length=30)),
                ('championTitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectText', models.CharField(blank=None, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ItemClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemClassRarity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
                ('chose', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemTypeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makeText', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patchNumber', models.CharField(max_length=20)),
                ('patchDate', models.DateTimeField(verbose_name='Date de publication')),
            ],
        ),
        migrations.CreateModel(
            name='RoleChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spellName', models.CharField(max_length=30)),
                ('spellBind', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statName', models.CharField(max_length=50)),
                ('statValue', models.IntegerField(default=0)),
                ('have', models.ManyToManyField(to='patchistiks.champions')),
                ('modify', models.ManyToManyField(through='patchistiks.Affect', to='patchistiks.patch')),
                ('put', models.ManyToManyField(to='patchistiks.effect')),
                ('will', models.ManyToManyField(to='patchistiks.items')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='got',
            field=models.ManyToManyField(to='patchistiks.itemtype'),
        ),
        migrations.AddField(
            model_name='effect',
            name='get',
            field=models.ManyToManyField(to='patchistiks.spell'),
        ),
        migrations.AddField(
            model_name='effect',
            name='make',
            field=models.ManyToManyField(to='patchistiks.items'),
        ),
        migrations.AddField(
            model_name='champions',
            name='are',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patchistiks.rolechamp'),
        ),
        migrations.AddField(
            model_name='champions',
            name='pick',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='champions',
            name='use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patchistiks.spell'),
        ),
        migrations.AddField(
            model_name='affect',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patchistiks.patch'),
        ),
        migrations.AddField(
            model_name='affect',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patchistiks.stats'),
        ),
    ]
